version: '2'
services:
  redis:
    image: redis:4-alpine
    stdin_open: true
    volumes:
    - mosmetro-redis:/data
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
  mosmetro:
    image: thedrhax/mosmetro-backend
    environment:
      MOSMETRO_ADMIN:
      MOSMETRO_ADMIN_USERNAME:
      MOSMETRO_ADMIN_PASSWORD:
      MOSMETRO_REDIS:
      MOSMETRO_STATSD:
      MOSMETRO_STATSD_PREFIX:
    links:
    - redis:redis
    - statsd:statsd
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
  influxdb:
    image: influxdb:alpine
    stdin_open: true
    volumes:
    - mosmetro-influxdb:/var/lib/influxdb
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=statistics
    environment:
      CONFIG_EVAL: |-
        if ! grep -q graphite /etc/influxdb/influxdb.conf; then
          echo [[graphite]];
          echo '  'enabled = true;
          echo '  'bind-address = \":2003\";
          echo '  'protocol = \"tcp\";
        fi
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL >> /etc/influxdb/influxdb.conf; /entrypoint.sh influxd
  influxdb-proxy:
    image: thedrhax/influxdb-timeshift-proxy
    environment:
      INFLUXDB: influxdb:8086
    stdin_open: true
    tty: true
    links:
    - influxdb:influxdb
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=statistics
  statsd:
    image: dsop/alpine-statsd:latest
    stdin_open: true
    tty: true
    links:
    - influxdb:influxdb
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
    environment:
      CONFIG_EVAL: |-
        sed -i 's/graphite.example.com/influxdb/g' /etc/statsd/config.js
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL; /usr/bin/node stats.js /etc/statsd/config.js
