version: '2'
services:
  redis:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  mosmetro:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  app:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  influxdb:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  influxdb-proxy:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  statsd:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
