version: '2'
services:
  redis:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  mosmetro:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
    upgrade_strategy:
      start_first: true
  influxdb:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  influxdb-proxy:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
  statsd:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
