version: '2'
services:
  memcached:
    image: memcached:alpine
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
  mosmetro:
    image: thedrhax/nginx-stateless:v0.1
    environment:
      CONFIG_LOCATION_0: location /releases { autoindex on; }
      FPM: 'true'
      FPM_HOST: backend
    stdin_open: true
    volumes:
    - mosmetro-www:/var/www/html
    - mosmetro-releases:/var/www/html/releases
    tty: true
    links:
    - memcached:memcached
    - influxdb:influxdb
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
      io.rancher.sidekicks: backend
  backend:
    image: thedrhax/mosmetro-backend
    stdin_open: true
    tty: true
    links:
    - memcached:memcached
    - influxdb:influxdb
    volumes_from:
    - mosmetro
  influxdb:
    image: influxdb
    stdin_open: true
    volumes:
    - mosmetro-influxdb:/var/lib/influxdb
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=backend

