version: '2'

services:
  memcached:
    image: memcached:alpine
    restart: always

  app:
    image: danieldent/php-7-fpm
    links:
      - memcached
    volumes:
      - ./html/:/var/www/html/
    command: sh -c "mkdir releases; chown www-data:www-data releases; php-fpm"
    restart: always

  nginx:
    image: thedrhax/nginx-stateless:v0.1
    ports:
      - 8080:80
    volumes_from:
      - app
    environment:
      CONFIG_LOCATION_0: location /releases { autoindex on; }
      FPM: 'true'
      FPM_HOST: app
    restart: always
