version: '2'
services:
  memcached:
    image: memcached:alpine
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
  mosmetro:
    image: thedrhax/nginx-stateless:v0.1
    environment:
      CONFIG_LOCATION_0: location /releases { autoindex on; }
      FPM: 'true'
      FPM_HOST: backend
    stdin_open: true
    volumes:
    - mosmetro-www:/var/www/html
    - mosmetro-releases:/var/www/html/releases
    tty: true
    links:
    - backend:backend
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
  backend:
    image: thedrhax/mosmetro-backend
    stdin_open: true
    tty: true
    links:
    - memcached:memcached
    - statsd:statsd
    volumes:
    - mosmetro-www:/var/www/html
    - mosmetro-releases:/var/www/html/releases
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
  influxdb:
    image: influxdb:alpine
    stdin_open: true
    volumes:
    - mosmetro-influxdb:/var/lib/influxdb
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
    environment:
      CONFIG_EVAL: |-
        if ! grep -q graphite /etc/influxdb/influxdb.conf; then
          echo [[graphite]];
          echo '  'enabled = true;
          echo '  'bind-address = \":2003\";
          echo '  'protocol = \"tcp\";
        fi
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL >> /etc/influxdb/influxdb.conf; /entrypoint.sh influxd
  influxdb-proxy:
    image: thedrhax/influxdb-timeshift-proxy
    environment:
      INFLUXDB: influxdb:8086
    stdin_open: true
    tty: true
    links:
    - influxdb:influxdb
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
  statsd:
    image: dsop/alpine-statsd:latest
    stdin_open: true
    tty: true
    links:
    - influxdb:influxdb
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
    environment:
      CONFIG_EVAL: |-
        sed -i 's/graphite.example.com/influxdb/g' /etc/statsd/config.js
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL; /usr/bin/node stats.js /etc/statsd/config.js
