version: '2'
services:
  memcached:
    image: memcached:alpine
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
  mosmetro:
    image: thedrhax/nginx-stateless:v0.1
    environment:
      CONFIG_LOCATION_0: location /releases { autoindex on; }
      FPM: 'true'
      FPM_HOST: backend
    stdin_open: true
    volumes:
    - mosmetro-www:/var/www/html
    - mosmetro-releases:/var/www/html/releases
    tty: true
    links:
    - memcached:memcached
    - statsd:statsd
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
      io.rancher.sidekicks: backend
  backend:
    image: thedrhax/mosmetro-backend
    stdin_open: true
    tty: true
    links:
    - memcached:memcached
    - statsd:statsd
    volumes_from:
    - mosmetro
  influxdb:
    image: influxdb:alpine
    stdin_open: true
    volumes:
    - mosmetro-influxdb:/var/lib/influxdb
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=backend
    environment:
      CONFIG_EVAL: |-
        if ! grep -q udp /etc/influxdb/influxdb.conf; then
          echo [[udp]];
          echo '  'enabled = true;
          echo '  'bind-address = \":8089\";
          echo '  'database = \"mosmetro\";
          echo '  'batch-size = 5000;
          echo '  'batch-timeout = \"1s\";
          echo '  'batch-pending = 10;
          echo '  'read-buffer = 0;
        fi
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL >> /etc/influxdb/influxdb.conf; /entrypoint.sh influxd
  statsd:
    image: dsop/alpine-statsd:latest
    stdin_open: true
    tty: true
    links:
    - influxdb:influxdb
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=frontend
    environment:
      CONFIG_EVAL: |-
        sed -i 's/graphite.example.com/influxdb/g' /etc/statsd/config.js
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL; /usr/bin/node stats.js /etc/statsd/config.js
  influxgraph:
    image: thedrhax/influxgraph
    stdin_open: true
    volumes:
    - /dev/shm/influxgraph-index:/srv/graphite
    tty: true
    links:
    - influxdb:influxdb
    - memcached:memcached
    labels:
      io.rancher.scheduler.affinity:host_label: mosmetro=backend
