version: '2'

services:
  influxdb:
    image: influxdb:alpine
    ports:
    - 8086:8086
    stdin_open: true
    volumes:
    - mosmetro-influxdb:/var/lib/influxdb
    restart: always
    environment:
      CONFIG_EVAL: |-
        if ! grep -q graphite /etc/influxdb/influxdb.conf; then
          echo [[graphite]];
          echo '  'enabled = true;
          echo '  'bind-address = \":2003\";
          echo '  'protocol = \"tcp\";
        fi
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL >> /etc/influxdb/influxdb.conf; /entrypoint.sh influxd

  statsd:
    image: dsop/alpine-statsd:latest
    stdin_open: true
    restart: always
    environment:
      CONFIG_EVAL: |-
        sed -i 's/graphite.example.com/influxdb/g' /etc/statsd/config.js
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL; /usr/bin/node stats.js /etc/statsd/config.js

  redis:
    image: redis:4-alpine
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: thedrhax/mosmetro-backend-dev
    ports:
      - 80:80
    volumes:
      - ./app:/app
    links:
      - redis:redis
    restart: always

volumes:
  mosmetro-influxdb:
