version: '2'

services:
  influxdb:
    image: influxdb:alpine
    ports:
    - 8086:8086
    stdin_open: true
    volumes:
    - influxdb:/var/lib/influxdb
    restart: always
    environment:
      INFLUXDB_DATA_QUERY_LOG_ENABLED: false
      INFLUXDB_GRAPHITE_ENABLED: true
      INFLUXDB_REPORTING_DISABLED: true

  statsd:
    image: dsop/alpine-statsd:latest
    stdin_open: true
    restart: always
    environment:
      CONFIG_EVAL: |-
        sed -i 's/graphite.example.com/influxdb/g' /etc/statsd/config.js
    entrypoint: /bin/sh
    command:
    - -c
    - eval $$CONFIG_EVAL; /usr/bin/node stats.js /etc/statsd/config.js

  redis:
    image: redis:4-alpine
    volumes:
      - redis:/data
    restart: always

volumes:
  influxdb:
  redis:
